/* Reversão: AZ-12094 (Plataforma2ASmart.Auth) — remove REFRESH_TOKEN e tabelas do Identity. Idempotente. */
SET XACT_ABORT ON;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS [REFRESH_TOKEN];
DROP TABLE IF EXISTS [AspNetUserTokens];
DROP TABLE IF EXISTS [AspNetUserRoles];
DROP TABLE IF EXISTS [AspNetUserLogins];
DROP TABLE IF EXISTS [AspNetUserClaims];
DROP TABLE IF EXISTS [AspNetRoleClaims];
DROP TABLE IF EXISTS [AspNetUsers];
DROP TABLE IF EXISTS [AspNetRoles];

COMMIT TRANSACTION;
